### ISSUE TITLE
Sending comments with unicode name makes the widget stay at "Sending ... "state

### ISSUE THREAD

**Issue by smbanaie** [JustComments/widget#11]
Hi 
first of all, I appreciate the useful widget you developed.
I just created my account and when a push Send button, it sucks at sending state.
when I came to the documentation this message was shown:
 👍 NoSuchKeyThe specified key does not exist

mojtaba.banaie@gmail.com 

can you help me?

**Comment by smbanaie** [comment]
you can try yourself 👍 
[My Personal Site Address](https://bit.ly/2OyV1Uj)

**Comment by OrKoN** [comment]
@smbanaie I just posted a comment successfully. Can you see the comment? It looks working for me. Please message me at alex@just-comments.com if you have further problems.  They don't seem to be directly related to the source code of the widget.

**Comment by smbanaie** [comment]
Thank you @OrKoN, the problem just Gone!

**Comment by smbanaie** [comment]
I came across this problem again and by testing various inputs, I finally realized that that the entering the Name (not the comment) in Persian causes this problem. I hint my website visitors to enter the name in English, but I hope this small problem will be solved quickly. thank you

**Comment by OrKoN** [comment]
@smbanaie Hey, could you try again and let me know if it works now?

**Comment by smbanaie** [comment]
Hi. I checked the issue and the problem was resolved.
Thank you very much for the speed and the hassle you took.

**Comment by OrKoN** [comment]
@smbanaie thanks a lot for reporting it!
