### ISSUE TITLE
Website issue: Link to this repo broken

### ISSUE THREAD

**Issue by AnandChowdhary** [JustComments/widget#46]
This is definitely not the right place to open an issue about this, but I figured it's the best way of letting you know.

The link to this repo on the "Learn more" link under "Advantages With JustComments" -> "Open Source" is broken on https://just-comments.com/. It links to https://just-comments.com/https:/github.com/justcomments/widget.

**Comment by OrKoN** [comment]
Thanks @AnandChowdhary! I have fixed it.
