### ISSUE TITLE
Push Notifications and Email Notifications have the same <title>

### ISSUE THREAD

**Issue by MatRouault** [JustComments/widget#51]
Hello Alex,

I've noticed that email and push notifications have the same "receive notifications about replies" <tilte> at the bottom of the comment form.

Of course, there are two differents symbols (the @ and the bell) but I'm not sure that these symbols are obvious enough for the vast majority of users.

Do you think it would be possible in the near future to have two different texts <title> ? Such as, for example :
- push notifications : <title>receive notifications about replies</title>
- email notifications : <title>receive an email when a new reply is posted</title>

Thanks again for JustComments ! :-)

**Comment by OrKoN** [comment]
@MatRouault Thanks for opening the issue! I have decided to update English and some other texts without waiting until I have translations for the rest of the languages. I have opened a PR here https://github.com/JustComments/widget/pull/52 Perhaps you could take a look and suggest the right wording for French?

**Comment by MatRouault** [comment]
Sure ! I'll do that very soon. Thanks ! :-)

**Comment by MatRouault** [comment]
@OrKoN Not sure how to suggest some modifications in your PR (don't know Github very well) so I post it here.
```
toggleNotificationsPush: 'Être informé des réponses via notification web',
toggleNotificationsEmail: 'Être informé des réponses par e-mail',
```
Also important : there's a typo in the translation for "Email" in the email input placeholder. It's not `émail` but `email` or `e-mail` ; no acute accent (émail means `Emaille` in french).

Hope it helps ! Keep up the good work. 👍

**Comment by OrKoN** [comment]
Thanks a lot for contributing the translation! I will publish the new version soon!
